[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/nyxos"]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "We don't have a map, but we have momentum. Let's see where this road goes."
readme = "README.md"
repository = "https://github.com/geyerandreas/nyxos"
license = "MIT"
keywords = ["python", "registry", "self-hosted"]

[workspace.dependencies]
axum = { version = "0.8.9" }
clap = { version = "4.6.6", features = ["derive"] }
nyxos-settings = { path = "./crates/settings", version = "0.1.0" }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.23" }
utoipa = { version = "5.5.0", features = ["axum_extras", "chrono"] }
utoipa-axum = { version = "0.2.0" }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }

[workspace.lints.clippy]
arithmetic_side_effects = "deny"
as_conversions = "deny"
exit = "deny"
expect_used = "deny"
indexing_slicing = "deny"
nursery = { level = "deny", priority = -1 }
panic = "deny"
panic_in_result_fn = "deny"
pedantic = { level = "deny", priority = -1 }
string_slice = "deny"
todo = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"
